spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/videochat?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test_user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: True
  aws:
    s3:
      credentials:
        accessKey: AKIA2PMNLBYQIY3AIBWB
        secretKey: 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
      bucket: minuawsbucket
      region:
        static: ap-northeast-2
      stack:
        auto: false
      end-point: s3.ap-northeast-2.amazonaws.com

  management:
    endpoints:
      web:
        exposure:
          include: "*"
