spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/videochat?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test_user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: True
cloud:
  aws:
    s3:
      bucket: minuawsbucket
      bucketUrl: https://minuawsbucket.s3.ap-northeast-2.amazonaws.com/
    credentials:
      accessKey: AKIA2PMNLBYQAEWU5RVG
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false




