spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/videochat?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test_user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: True
cloud:
  aws:
    s3:
      bucket: minuawsbucket
      bucketUrl: s3://minuawsbucket/image/
    credentials:
      access-key: AKIA2PMNLBYQIY3AIBWB
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false




