name: CD

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application.yml
      - name: make application-prod.yaml
        run: |
          cd ./src/main/resources
          touch ./application.yaml
          echo "${{ secrets.APPLICATION_PRO }}" > ./application.yaml


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --push --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/chat .
          # docker tag chat ${{ secrets.DOCKER_USERNAME }}/chat
          docker push ${{ secrets.DOCKER_USERNAME }}/chat

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }} # pem 키

          script: |
            docker rm $(docker ps --filter 'status=exited' -a -q)
            docker pull ${{ secrets.DOCKER_USERNAME }}/chat
            docker-compose up -d
            docker run -d --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/chat
            docker image prune -a -f
